name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch
    steps:
    - uses: actions/checkout@v2
    - name: Bundle
      run: npx gulp bundle
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ui-bundle
        path: build/ui-bundle.zip
