name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install

  verify:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: node_modules/.bin/gulp lint

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    container:
      image: node:10.14.2-stretch
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Bundle
      run: node_modules/.bin/gulp bundle
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ui-bundle
        path: build/ui-bundle.zip
